# Generated by Django 5.2.8 on 2025-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
