# Generated by Django 5.2.8 on 2025-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data',
            new_name='data_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_cobranca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='external_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(default='pix', max_length=20),
            preserve_default=False,
        ),
    ]
